# description of this workflow, can be anything you want
name: Package and release

# we need to let GitHub know _when_ we want to release, typically only when we create a new tag.
# this will target only tags, and not all pushes to the master branch.
# this part can be heavily customized to your liking, like targeting only tags that match a certain word,
# other branches or even pullrequests.
on:
  push:
    tags:
      - '**'

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  release:
    runs-on: ubuntu-latest

    # env:
    #   CF_API_KEY: ${{ secrets.CF_API_KEY }}
    #   WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
    #   WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    #   GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  

    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # gets git history for changelogs

      # - name: Run Luacheck
      #   uses: nebularg/actions-luacheck@v1
      #   with:
      #     args: "--no-color -q"
      #     annotate: error

      - name: Package and release
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        with:
          args: -w 0 -p 0